// <auto-generated />
using System;
using GGinfoSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GGinfoSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GGinfoSite.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SignupDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AppUserID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GGinfoSite.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PostRating")
                        .HasColumnType("int");

                    b.Property<string>("PostText")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostTitle")
                        .HasColumnType("longtext");

                    b.Property<int?>("PosterAppUserID")
                        .HasColumnType("int");

                    b.HasKey("BlogPostID");

                    b.HasIndex("PosterAppUserID");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("GGinfoSite.Models.BlogPost", b =>
                {
                    b.HasOne("GGinfoSite.Models.AppUser", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterAppUserID");

                    b.Navigation("Poster");
                });
#pragma warning restore 612, 618
        }
    }
}
